spring.profiles.active=dev

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# DATABASE (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/jobportalsystem
spring.datasource.username=root
spring.datasource.password=123456

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto= create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

## ===============================
## LOGGING (optional)
## ===============================
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#
## ===============================
# JWT (t? define)
# ===============================
jwt.secret=mySecretKeyForJWTTokenGenerationAndValidation2025JobPortalSystem
jwt.expiration=86400000

## ===============================
## FILE UPLOAD
## ===============================
#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.max-request-size=10MB
#
## ===============================
## MAIL (optional - Day 12)
## ===============================
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=your-email@gmail.com
#spring.mail.password=your-app-password
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true